### ISSUE TITLE
feature request: two sets of settings; separate light mode and dark mode

### ISSUE THREAD

**Issue by n6id** [tjbrennan/obsidian-color-cycler#1]
im loving color cycler, but im needing to adjust the color settings whenever i switch between dark and light mode to be able to see certain stuff and have a color scheme that i like (which involves automatically revolving thru the whole color spectrum slowly: increment, one second one degree. its gorgeous.) 
i would just need to be able to adjust hue&saturation connected to the light/dark settings of obsidian for this to work for me personally. 
it would be wonderful to be able to have this switchover for the color cycler settings between light/dark done automatically; i already have obsidian set up to switch between light and dark theme automatically with the day and night plugin.
thanks for the awesome plugin! :)

**Comment by tjbrennan** [comment]
Glad you're enjoying the plugin, and thanks for the feedback! This is a good idea and I'm going to think about the best way to implement it. I'll be sure to let you know when it's done!

**Comment by tjbrennan** [comment]
Hi @single-effect-event, sorry for the long delay getting this feature out. It ended up being quite a large overhaul to the way the settings are stored, but I think it's working well. Give it a try and let me know if you find any bugs. Thanks!

**Comment by n6id** [comment]
this is awesome, thank you so much!!
i set it up yesterday and looks good so far :)
