### ISSUE TITLE
Plugin does not compile

### ISSUE THREAD

**Issue by nicodominguezvlk** [tjbrennan/obsidian-color-cycler#3]
**Bug description:**
The plugin simply fails to load on last versions of Obsidian.

**To reproduce:**
- Download Obsidian
- Create a new vault
- Enable Community Plugins
- Search for "Color cycler" and install it
- Enable Color cycler
And it doesn't do anything. When it did, it added the logo on the ribbon bar, and allowed to configure the plugin settings.

**Happened on:**
- Ubuntu 24 x64
- Windows 11 x64
- Xubuntu 22 x64

**IMPORTANT:** It seems that copying the data.js file from a functional vault to the plugin folder of the new vault fixes the problem. The issue probably comes when trying to creating this file, which does not happen.

**Comment by tjbrennan** [comment]
@nicodominguezvlk thank you for notifying me about this and for helping to debug it. I was able to reproduce the issue and I'll work on a fix as soon as possible!

**Comment by tjbrennan** [comment]
Hey @nicodominguezvlk, I've released version 1.1.1 that should resolve this. Please let me know if it is not resolved or if you encounter any more issues. Thanks again for pointing out this showstopper bug, I sincerely appreciate it!

**Comment by nicodominguezvlk** [comment]
Thank you @tjbrennan for fixing it! It works great now on new installations as well. I love this plugin and will keep trying to help with anything!
